version: 1.3.0.{build}
skip_branch_with_pr: true
skip_tags: false
environment:
  fast_finish: true
install:
- cmd: choco install 7zip.commandline
cache:
- C:\ProgramData\chocolatey\lib
- C:\ProgramData\chocolatey\bin
build_script:
- cmd: 7za a -bb0 dummy.miz C:\projects\ATRM\* -xr!.git -x!*.miz -x!*.yml
- cmd: IF /I "%APPVEYOR_REPO_TAG%"=="true" (ren dummy.miz ATRM%APPVEYOR_REPO_TAG_NAME%.miz) ELSE (ren dummy.miz ATRM_%APPVEYOR_BUILD_VERSION%.miz)
test: off
artifacts:
- path: '*.miz'
  name: ATRM
deploy:
- provider: GitHub
  auth_token:
    secure: oqhY5z4JkQh4bNg2w52lZ5+XL6WOoJxwkfhXBUdwvThrqT+4rX5QsN7DmP9MuRTa
  artifact: 'ATRM'
  draft: false
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true